config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get "home/about" => "homes#about",as: "about"


  resources :users, only: [:show, :edit, :new, :index, :create, :update] do
    resource :relationships, only: [:create]
    delete "relationships" =>'relationships#destroy', as: 'relationship'
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :books, only: [:show, :edit, :new, :index, :create,:update, :destroy]
  resources :chats, only: [:show, :create]
 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

end

app/models/chat.rb
class Chat < ApplicationRecord
  
  belongs_to :user
  belongs_to :room
  
  validates :message, presence: true, length: { maximum: 140 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  
  has_many :chats
  has_many :user_rooms
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms #roomsには直接繋がれない為user_roomsを通す
  
  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed
  

  has_one_attached :profile_image

  validates :name,  uniqueness: true, length: { minimum:2, maximum: 20 }
  validates :introduction,  length: { maximum: 50 }



  def get_profile_image(width,hight)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end
  
  def follow(user)
    relationships.create(followed_id: user.id)
  end
  
  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy#特定の条件にマッチした最初のレコードを検索し取得できるデータは1件
  end
  
  def following?(user)
    followings.include?(user)#関連するテーブルをまとめて取得
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @users = User.all
  end

  def show
    @book = Book.find(params[:id])
    @book_user = @book.user
    @book_new = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    login_user_id = current_user.id
    if(@book.user_id != login_user_id)
      redirect_to books_path
    end
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] ="You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book= Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end


  private

    def book_params
      params.require(:book).permit(:title, :body)
    end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :reject_non_related, only: [:show]
  
  def show
  @user = User.find(params[:id])
  rooms = current_user.user_rooms.pluck(:room_id)
  user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

  if user_rooms.nil?
   @room = Room.new
   @room.save
   UserRoom.create(user_id: @user.id, room_id: @room.id)
   UserRoom.create(user_id: current_user.id, room_id: @room.id)
  else
   @room = user_rooms.room
  end

  @chats = @room.chats
  @chat = Chat.new(room_id: @room.id)
  end

 def create
    @chat = current_user.chats.new(chat_params)
    render :validater unless @chat.save
 end

 private

 def chat_params
  params.require(:chat).permit(:message, :room_id)
 end
 
 def reject_non_related #相互フォローかどうかをみている
    user = User.find(params[:id])
    unless current_user.following?(user) && user.following?(current_user)
      redirect_to books_path
    end
 end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationship_controller.rb
class RelationshipController < ApplicationController
  before_action :authenticate_user!
  
  def create
    user = User.find(params[:user_id])
    current_user.follow(user)
    redirect_to request.referer #遷移元のURLに戻る
  end
  
  def destroy
    user = User.find(params[:user_id])
    current_user.unfollow(user)
    redirect_to request.referer
  end
  
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end
  
  def follower
    user = User.find(params[:user_id])
    @users = user.follower
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  
  before_action :authenticate_user!
  
  def create
    user = User.find(params[:user_id])
    current_user.follow(user)
    redirect_to request.referer #遷移元のURLに戻る
  end
  
  def destroy
    user = User.find(params[:user_id])
    current_user.unfollow(user)
    redirect_to request.referer
  end
  
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end
  
  def follower
    user = User.find(params[:user_id])
    @users = user.follower
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
  @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'Welcome! You have signed up successfully.'
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    user_id = params[:id].to_i
    login_user_id = current_user.id
    if(user_id != login_user_id)
      redirect_to user_path(current_user)
    end
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "You have updated user successfully."
       redirect_to user_path(@user.id)
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
 
 
 <%= link_to edit_user_path(user.id), class:"btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
  

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1 class="mt-3">Editing Book</h1>

      <% if @book.errors.any? %>
      <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
      <ul>
        <%= @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
      <% end %>

      <%=form_with model: @book do |f| %>
      <div class="pb-3">
        <label for="book_title">Title</label>
        <%= f.text_field :title, size: "50"%>
      </div>
      <div>
        <label for="book_body">Opinion</label>
        <%= f.text_area :body, size: "50"%>
      </div>
      <%= f.submit "Update Book", class: "btn btn-success"%>
      <% end %>
      
      <%=link_to "Show", book_path(@book.id) %>
      |
      <%=link_to "Back", books_path %>
    </div>
  </div>
 </div>
 
 
 

app/views/books/index.html.erb
<div><%= flash[:notice] %></div>

<main>
  <% if @book.errors.any? %>
    <%= @book.errors.count %>errors prohibited this obj from being saved:
      <ul>
      <%= @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
  <% end %>

  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        
      　<%=render 'users/info', user: current_user %>
      　<h2 class="mt-3">New book</h2>
        <%= render 'books/form', book: @book %>
      </div>
      <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
        <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to  user_path(book.user.id) do %>
              <%= image_tag book.user.get_profile_image(100,100) %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
   </div>
  </div>
</div>
</main>

app/views/books/show.html.erb
<div><%= flash[:notice] %></div>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
      <h2>User info</h2>
      <%=render 'users/info', book: @book_new, user: @book_user%>
      <h2 class="mt-3">New book</h2>
        <%= render 'books/form', book: @book %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2 class="mt-3">Book detail</h2>
        <table class="table">
          <tbody>
            <tr>
              <td><%= image_tag @book.user.get_profile_image(100,100)%>
                  <%= link_to @book.user.name, user_path(@book.user.id) %>
              </td>
              <td><%= link_to @book.title, book_path %></td>
              <td><%= @book.body %></td>
              <td>
                <% if @book.user == current_user %>
                <%=link_to "Edit", edit_book_path, class: 'btn btn-sm btn-success' %>
                <% end %>
              </td>
              <td>
                <% if @book.user == current_user %>
                <%=link_to "Destroy", book_path, method: :delete, class: 'btn btn-sm btn-danger', "data-confirm" => "本当に消しますか？" %>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/chats/create.js.erb
$('.message').append("<p style='text-align: left;'><%= @chat.message %></p>");
$('input[type=text]').val("")
$('error-alert').empty();

app/views/chats/show.html.erb
<h1 id="room" data-room="<%= @room.id %>" data-user="<%= current_user.id %>">
<%= @user.name %> さんとのチャット</h1>

<div class="message" style="width: 400px;">
  <% @chats.each do |chat| %>
    <% if chat.user_id == current_user.id %>
      <p style="text-align: right;"><%= chat.message %></p>
    <% else %>
      <p style="text-align: left;"><%= chat.message %></p>
    <% end %>
  <% end %>
</div>

<div class="errors">
  <%= render "layouts/errors", obj: @chat %>
</div>

<%= form_with model: @chat, local:false  do |f| %>
  <%= f.text_field :message %>
  <%= f.hidden_field :room_id %>
<% end %>

app/views/chats/validater.js.erb
$('.errors').html("<%= j(render 'layouts/errors', obj: @chat) %>");

app/views/homes/about.html.erb
<main>
  <div class="container">
    <div class="low">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1 class="mt-3 mx-auto text-center">
          Welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        !
        </h1>
      </div>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <div><%= flash[:notice] %></div>

  <div class="container">
    <div class="low">
      <div class="mx-auto mt-3 col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        !!
        </h1>
        <p>In
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        ,</p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>

        <div class="btn-wrapper col-10 mx-auto">
          <div class="low">
            <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in"  %>
          </div>
          <div class="low">
            <%= link_to"Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_in" %>
          </div>
        </div>
        
      </div>
    </div>
  </div>
</main>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              
              <% if user_signed_in? %>
          　     <li>
                  <i class="fas fa-home" style="color:#fff;" ></i>
                  <%= link_to "Home", user_path(current_user.id), class:"text-light" %>
                </li>
                <li class="mx-2">
                  <i class="fas fa-users" style="color:#fff;"></i>
                  <%= link_to "Users", users_path, class:"text-light" %>
                </li>
                <li class="mx-2">
                  <i class="fas fa-book-open" style="color:#fff;"></i>
                  <%= link_to "Books", books_path, class:"text-light" %>
                </li>
                <li class="nav-item">
                 <i class="fas fa-sign-out-alt" style="color:#fff;" ></i>
                  <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"text-light" %>
                </li>
              <% else %>
              　<li>
              　  <i class="fas fa-home" style="color:#fff; "></i>
                 <%= link_to "Home", root_path, class:"text-light" %>
                </li>
                <li class="mx-2">
                   <i class="fas fa-link" style="color:#fff;"></i>
                  <%= link_to "About", about_path, class:"text-light" %>
                </li>
                <li class="mx-2">
                   <i class="fas fa-user-plus" style="color:#fff;"></i>
                  <%= link_to "Sign up", new_user_registration_path, class:"text-light" %>
                </li>
                <li>
                   <i class="fas fa-sign-in-alt" style="color:#fff;"></i>
                  <%= link_to "Log in", new_user_session_path, class:"text-light" %>
                </li>
          　　  <% end %>
            </ul>
          </div>
        </div>
      </nav>
  </header>
  
   <%= yield %>
   
  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
  </body>
</html>

app/views/relationships/_btn.html.erb
<% if current_user != user %>
  <% if current_user.following?(user) %>
    <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
  <% end %>
<% end %>

app/views/relationships/followers.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/_index.html.erb
<table class="table ">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td>フォロー数：<%= user.followings.count %></td>
      <td>フォロワー数：<%= user.followers.count %></td>
      <td><%= render "relationships/btn", user: user %></td>
      <td><%= link_to "Show", user_path(user.id) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image(100,100) %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>
　
<div class='row'>
  <% if current_user != user %>
    <td><%= render "relationships/btn", user: user %></td>
  <% else %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% end %>
  
  <% if current_user != user && current_user.following?(user) && user.following?(current_user) %>
    <%= link_to 'chatを始める', chat_path(user.id), class: "ml-3" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2 class="mt-3">User info</h2>

      <% if @user.errors.any? %>
      <h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
      <% end %>

      <%=form_with model:@user do |f| %>
      <div class="pb-3">
        <label for="user_name">Name</label>
        <%= f.text_field :name, size: "50"%>
      </div>
      <div>
        <label for="user_image">Image</label>
      </div>
      <div  class="pb-3">
        <%= f.file_field :profile_image, accept: "image/*" %>
      </div>
      <div>
        <label for="user_introduction">Introduction</label>
        <%= f.text_area :introduction, size: "50"%>
      </div>
      <div>
        <%= f.submit"Update User", class:"btn btn-secondary" %>
      </div>
      <% end %>

    </div>
  </div>
 </div>

app/views/users/index.html.erb
<main>
  <%= flash[:notice] %>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
      <h2>User info</h2>
      <%=render 'info', book: @book, user: current_user %>
      <h2 class="mt-3">New book</h2>
        <%= render 'books/form', book: @book %>
      </div>
      <div class="col-md-8 offset-md-1">
      <h2 class="mt-3">Users</h2>
        <%= render 'index', users: @users %>
     </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<%= flash[:notice] %>
<main>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
      <h2>User info</h2>
      <%=render 'info', book: @book, user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: Book.new %>
      </div>

      <div class="col-md-8 offset-md-1">
      <h2 class="mt-3">Books</h2>
        <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
     </div>
    </div>
  </div>
</main>